/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_wiev;

import Backend.Banka;
import Backend.Ceo;
import Backend.Kasa;
import Backend.Personel;
import Backend.Sube;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import veritabani.Veritabani;
import static veritabani.Veritabani.conn;

/**
 *
 * @author yahya
 */
public class bankaOlusturGUI extends javax.swing.JFrame {

    public Banka b1 = new Banka();
    public Personel p1 = new Personel();
    public Kasa k1 = new Kasa();

    public bankaOlusturGUI() {
        initComponents();
    }

    public bankaOlusturGUI(Personel p, Banka b, Kasa k) {
        initComponents();
        b1 = b;
        p1 = p;
        k1 = k;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        subekonumtext = new javax.swing.JTextField();
        ceoisimtext = new javax.swing.JTextField();
        ceosoyisimtext = new javax.swing.JTextField();
        ceotctext = new javax.swing.JTextField();
        ceosifretext = new javax.swing.JPasswordField();
        olusturbuton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("banka oluştur ek sayfa");
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);

        jLabel1.setText("İLK SUBEYİ  EKLE:");

        jLabel2.setText("KONUM:");

        jLabel4.setText("CEO BİLGİLERİ:");

        jLabel5.setText("CEO ADI: ");

        jLabel6.setText("CEO TC NO: ");

        jLabel7.setText("CEO SOY ADI: ");

        jLabel8.setText("CEO ŞİFRE BELİRLE: ");

        subekonumtext.setToolTipText("");

        olusturbuton.setText("OLUŞTUR");
        olusturbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olusturbutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(olusturbuton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subekonumtext)
                            .addComponent(ceoisimtext)
                            .addComponent(ceosoyisimtext)
                            .addComponent(ceotctext, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(ceosifretext))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(subekonumtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ceoisimtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ceosoyisimtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ceotctext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ceosifretext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(olusturbuton)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void olusturbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olusturbutonActionPerformed
        int[] x = {subekonumtext.getText().length(), ceoisimtext.getText().length(), ceosoyisimtext.getText().length(), ceotctext.getText().length(), ceosifretext.getText().length()};
        int kontrol = 0;
        for (int i = 0; i < x.length; i++) {
            if (x[i] == 0) {
                kontrol++;
                break;
            }
        }
        if (kontrol > 0) {
            JOptionPane.showMessageDialog(null, "lütfen tüm alanları eksiksiz doldurunuz! ");
        } else {
            String konum = subekonumtext.getText();
            String ceoisim = ceoisimtext.getText();
            String ceosoyisim = ceosoyisimtext.getText();
            String ceotc = ceotctext.getText();
            String ceosifre = ceosifretext.getText();

            Veritabani.baglan();

            String sorgu = "INSERT INTO subeler(ceoismi,konum) VALUES (?,?)";
            PreparedStatement ps;
            String sorgu2 = "INSERT INTO yetkili(tcno,isim,sifre,soyisim,unvan)VALUES(?,?,?,?,?)";
            String c = "ceo";
            PreparedStatement ps2;
            int res = JOptionPane.showConfirmDialog(null, "banka oluşturulacak onaylıyor musunuz", "onayla", JOptionPane.YES_NO_OPTION);
            if (res == 0) {
                try {
                    ps = conn.prepareStatement(sorgu);
                    ps2 = conn.prepareStatement(sorgu2);
                    ps.setString(1, ceoisim);
                    ps.setString(2, konum);
                    ps2.setString(1, ceotc);
                    ps2.setString(2, ceoisim);
                    ps2.setString(3, ceosifre);
                    ps2.setString(4, ceosoyisim);
                    ps2.setString(5, c);
                    ps2.executeUpdate();
                    ps.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(MainPageGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                String sahipekle = "INSERT INTO yetkili (tcno,isim,sifre,soyisim,unvan) VALUES (?,?,?,?,?)";
                String unvansahip = "sahip";
                Veritabani.baglan();
                try {
                    PreparedStatement yps = conn.prepareStatement(sahipekle);
                    yps.setString(1, p1.getTc());
                    yps.setString(2, p1.getIsim());
                    yps.setString(3, p1.getSifre());
                    yps.setString(4, p1.getSoyisim());
                    yps.setString(5, unvansahip);

                    yps.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(MainPageGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                String bankaekle = "INSERT INTO banka(isim) VALUES (?)";
                try {
                    PreparedStatement bps = conn.prepareStatement(bankaekle);
                    bps.setString(1, b1.getIsim());
                    bps.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(MainPageGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                String kasa = "INSERT INTO kasa (bankaadi,tl,dolar) VALUES (?,?,?)";
                try {
                    PreparedStatement kps = conn.prepareStatement(kasa);
                    kps.setString(1, b1.getIsim());
                    kps.setDouble(2, k1.getPara());
                    kps.setDouble(3, 0.0);
                    kps.executeUpdate();

                } catch (SQLException ex) {
                    Logger.getLogger(MainPageGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                String mesaj = b1.getIsim() + " adlı bankanız oluşturuldu. " + k1.getPara() + " kadar para kasaya eklendi. " + ceoisimtext.getText()
                        + " adlı ceo " + konum + "  şubesine atandı. ";
                JOptionPane.showMessageDialog(null, mesaj);
                new MainPageGUI().setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "işleminiz iptal edildi");
                new MainPageGUI().setVisible(true);
                dispose();
            }

        }
    }//GEN-LAST:event_olusturbutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bankaOlusturGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bankaOlusturGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bankaOlusturGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bankaOlusturGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bankaOlusturGUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ceoisimtext;
    private javax.swing.JPasswordField ceosifretext;
    private javax.swing.JTextField ceosoyisimtext;
    private javax.swing.JTextField ceotctext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton olusturbuton;
    private javax.swing.JTextField subekonumtext;
    // End of variables declaration//GEN-END:variables
}
