/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_wiev;

import Backend.Musteri;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class KreditalebiGUI extends javax.swing.JFrame {

    String tcno;
    String isim;
    Double para;
    String unvan;
    public KreditalebiGUI() {
        initComponents();
    }

    public KreditalebiGUI(Musteri m) {
        initComponents();
        tcno = m.getTc();
        isim = m.getIsim();
        para = m.getVarlik();
        unvan = m.getUnvan();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        kretiturucombobox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        aylikgelirtext = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        taksitsayisicombobox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        kreditutaricombobox = new javax.swing.JComboBox<>();
        sozlesmecheckbox = new javax.swing.JCheckBox();
        basvurbuton = new javax.swing.JButton();
        cikisbuton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KREDİ TALEBİ");
        setResizable(false);

        jLabel1.setText("Kredi talebi ekranına hoş geldiniz!");

        kretiturucombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kredi türünü seçiniz", "ihtiyaç kredisi", "konut kredisi", "taşıt kredisi", "ziraa ikredi", " " }));

        jLabel2.setText("aylık sabit geliriniz: ");

        aylikgelirtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aylikgelirtextActionPerformed(evt);
            }
        });

        jLabel3.setText("kaç taksitle ödemek istersiniz: ");

        taksitsayisicombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "taksit sayısı", "3(%1.05 faiz)", "6(%1.1 faiz)", "12(%1.4 faiz)", "24(%1.6 faiz)", "36(%1.8 faiz)" }));

        jLabel4.setText("kredi tutarı : ");

        kreditutaricombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kredi tutarı", "3000", "5000", "10000", "50000", "100000", "200000" }));

        sozlesmecheckbox.setText("sözleşmeyi kabul eidyorum");

        basvurbuton.setText("başvur");
        basvurbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basvurbutonActionPerformed(evt);
            }
        });

        cikisbuton.setText("çıkış");
        cikisbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisbutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kreditutaricombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(aylikgelirtext, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(taksitsayisicombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sozlesmecheckbox)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kretiturucombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cikisbuton)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(basvurbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cikisbuton))
                        .addGap(18, 18, 18)
                        .addComponent(kretiturucombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aylikgelirtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(taksitsayisicombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGap(33, 33, 33)
                .addComponent(kreditutaricombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sozlesmecheckbox)
                .addGap(12, 12, 12)
                .addComponent(basvurbuton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aylikgelirtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aylikgelirtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aylikgelirtextActionPerformed

    private void basvurbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basvurbutonActionPerformed
        if (kretiturucombobox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "lütfen kredi türünü seçiniz");
        } else if (aylikgelirtext.getText().length() == 0 || Integer.parseInt(aylikgelirtext.getText()) <= 0) {
            JOptionPane.showMessageDialog(null, "lütfen geçerli bir aylık gelir giriniz");
        } else if (taksitsayisicombobox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "lütfen taksit sayısını seçiniz! ");
        } else if (kreditutaricombobox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "lütfen kredi tutarını belirleyiniz! ");
        } else if (!sozlesmecheckbox.isSelected()) {
            JOptionPane.showMessageDialog(null, "lütfen sözleşmeyi onaylayınız ");
        } else {
            int tutar = Integer.parseInt((String) kreditutaricombobox.getSelectedItem());
            int sure = taksitsayisicombobox.getSelectedIndex();
            int odemesuresi = 0;

            double odenecekmiktar = 0;
            switch (sure) {
                case 1:
                    odenecekmiktar = (tutar * 1.05 / 100) + tutar;
                    odemesuresi = 3;
                    break;
                case 2:
                    odenecekmiktar = (tutar * 1.1 / 100) + tutar;
                    odemesuresi = 6;
                    break;
                case 3:
                    odenecekmiktar = (tutar * 1.4 / 100) + tutar;
                    odemesuresi = 12;
                    break;
                case 4:
                    odenecekmiktar = (tutar * 1.6 / 100) + tutar;
                    odemesuresi = 24;
                    break;
                case 5:
                    odenecekmiktar = (tutar * 1.6 / 100) + tutar;
                    odemesuresi = 36;
                    break;
                default:
                    odenecekmiktar = tutar;
            }

            String mesaj = "kreti tutarınız: " + Integer.toString(tutar) + " ödeyeceğiniz miktar: " + Double.toString(odenecekmiktar)
                    + " ödenecek süre: " + Integer.toString(odemesuresi) + " onaylıyor musunuz ?";
            int res = JOptionPane.showConfirmDialog(null, mesaj, "baslik", JOptionPane.YES_NO_OPTION);
            int kreditutari = kreditutaricombobox.getSelectedIndex();
            int kredimiktar = 0;
            switch (kreditutari) {
                case 1:
                    kredimiktar = 3000;
                    break;
                case 2:
                    kredimiktar = 5000;
                    break;
                case 3:
                    kredimiktar = 10000;
                    break;
                case 4:
                    kredimiktar = 50000;
                    break;
                case 5:
                    kredimiktar = 100000;
                    break;
                case 6:
                    kredimiktar = 200000;
                    break;
                default:
                    kredimiktar=0;
            }

            if (res == 0) {
                try {
                    Musteri m = new Musteri();
                    m.kredibasvurusu(tcno, isim, (String) kretiturucombobox.getSelectedItem(), aylikgelirtext.getText(), odemesuresi, kredimiktar);
                    JOptionPane.showMessageDialog(null, "başvurunuz iletilmiştir, ileti durumunu size bildireceğiz");
                    m.setTc(tcno);
                    m.setVarlik(para);
                    MusteriGUI mg = new MusteriGUI(m);
                    mg.setVisible(true);
                    dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(KreditalebiGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "işleminiz iptal edildi");
            }
        }
    }//GEN-LAST:event_basvurbutonActionPerformed

    private void cikisbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisbutonActionPerformed
        try {
            Musteri m = new Musteri();
            m.setTc(tcno);
            m.setVarlik(para);
            MusteriGUI mg = new MusteriGUI(m);
            mg.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(KreditalebiGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cikisbutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KreditalebiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KreditalebiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KreditalebiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KreditalebiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KreditalebiGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aylikgelirtext;
    private javax.swing.JButton basvurbuton;
    private javax.swing.JButton cikisbuton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> kreditutaricombobox;
    private javax.swing.JComboBox<String> kretiturucombobox;
    private javax.swing.JCheckBox sozlesmecheckbox;
    private javax.swing.JComboBox<String> taksitsayisicombobox;
    // End of variables declaration//GEN-END:variables
}
