/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_wiev;

import Backend.Musteri;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author yahya
 */
public class KrediKartiBasvurGUI extends javax.swing.JFrame {

    /**
     * Creates new form KrediKartiBasvurGUI
     */
    String isim = null;
    String tc = null;
    double para = 0;
    String unvan = "diger";

    public KrediKartiBasvurGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public KrediKartiBasvurGUI(Musteri m) {
        initComponents();
        tc = m.getTc();
        isim = m.getIsim();
        para = m.getVarlik();
        unvan = m.getUnvan();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        kartturucombobox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        aylikgelirtextbox = new javax.swing.JTextField();
        sozlesmecheckbox = new javax.swing.JCheckBox();
        basvuruyapbuton = new javax.swing.JButton();
        cikisbuton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("kredi kartı başvurusu");

        jLabel1.setText("KREDİ KARTI BAŞVURUSU ");

        kartturucombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kart türü", "üni kart", "çiftçi kart", "normal kart" }));

        jLabel2.setText("aylık gelir : ");

        sozlesmecheckbox.setText("sözleşmeyi onaylıyor musunuz ?");
        sozlesmecheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sozlesmecheckboxActionPerformed(evt);
            }
        });

        basvuruyapbuton.setText("başvuru yap");
        basvuruyapbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basvuruyapbutonActionPerformed(evt);
            }
        });

        cikisbuton.setText("çıkış");
        cikisbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisbutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kartturucombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(sozlesmecheckbox)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(aylikgelirtextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(basvuruyapbuton)))))
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cikisbuton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(kartturucombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(aylikgelirtextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(sozlesmecheckbox)
                .addGap(18, 18, 18)
                .addComponent(basvuruyapbuton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(cikisbuton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sozlesmecheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sozlesmecheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sozlesmecheckboxActionPerformed

    private void basvuruyapbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basvuruyapbutonActionPerformed
        String kartbasvurusu = " bilgi yok";
        Musteri m = new Musteri();
        m.setTc(tc);
        m.setUnvan(unvan);
        m.setIsim(isim);
        m.setVarlik(para);
        if (kartturucombobox.getSelectedIndex() == 0 || aylikgelirtextbox.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "lütfen gerekli yerleri doldurunuz ");
        } else if (!sozlesmecheckbox.isSelected()) {
            JOptionPane.showMessageDialog(null, "sözleşmeyi onaylayınız ");
        } else if (!unvan.equals("öğrenci") && kartturucombobox.getSelectedIndex() == 1) {
            JOptionPane.showMessageDialog(null, "öğrenci kartına sadece öğrenciler başvurabilir!");
        } else if (!unvan.equals("çiftçi") && kartturucombobox.getSelectedIndex() == 2) {
            JOptionPane.showMessageDialog(null, "çiftçi kartına sadece çiftçiler başvurabilir!");
        } else {
            int res = JOptionPane.showConfirmDialog(null, "kart başvurunuzu onaylıyor musunuz?", "onayla", JOptionPane.YES_NO_OPTION);
            if (res == 0) {
                try {

                    String karttur = (String) kartturucombobox.getSelectedItem();
                    double gelir = Double.parseDouble(aylikgelirtextbox.getText());
                    m.kredikartibasvur(tc, isim, karttur, gelir, unvan);
                    JOptionPane.showMessageDialog(null, "kart başvurunuz alınmıştır onay süreci biraz zaman alabilir! ");
                    kartbasvurusu = (String) kartturucombobox.getSelectedItem() + "basvurusu alındı bekleniyor";
                    MusteriGUI mg = new MusteriGUI(m, kartbasvurusu);
                    mg.setVisible(true);
                    dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(KrediKartiBasvurGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    JOptionPane.showMessageDialog(null, "işleminiz iptal edilmiştir");
                    m.setTc(tc);
                    m.setUnvan(unvan);
                    m.setIsim(isim);
                    m.setVarlik(para);
                    kartbasvurusu = "kart başvurusu yok";
                    MusteriGUI mg = new MusteriGUI(m, kartbasvurusu);
                    mg.setVisible(true);
                    dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(KrediKartiBasvurGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_basvuruyapbutonActionPerformed

    private void cikisbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisbutonActionPerformed
        try {
            Musteri m = new Musteri();
            m.setTc(tc);
            m.setUnvan(unvan);
            m.setIsim(isim);
            m.setVarlik(para);
            MusteriGUI mg = new MusteriGUI(m);
            mg.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(KrediKartiBasvurGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cikisbutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KrediKartiBasvurGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KrediKartiBasvurGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KrediKartiBasvurGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KrediKartiBasvurGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KrediKartiBasvurGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aylikgelirtextbox;
    private javax.swing.JButton basvuruyapbuton;
    private javax.swing.JButton cikisbuton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> kartturucombobox;
    private javax.swing.JCheckBox sozlesmecheckbox;
    // End of variables declaration//GEN-END:variables
}
