/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_wiev;

import Backend.Musteri;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import veritabani.Veritabani;
import static veritabani.Veritabani.conn;

/**
 *
 * @author yahya
 */
public class MusteriLoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form MusteriGUI
     */
    public MusteriLoginGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        musteritctext = new javax.swing.JTextField();
        musterisifretext = new javax.swing.JPasswordField();
        musterigirisbuton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        musterilogincıkısbuton = new javax.swing.JButton();
        girislog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Musteri login");
        setResizable(false);

        jLabel4.setText("musteri girişi");

        musteritctext.setBackground(new java.awt.Color(255, 255, 255));
        musteritctext.setForeground(new java.awt.Color(0, 0, 0));
        musteritctext.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        musteritctext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteritctextActionPerformed(evt);
            }
        });

        musterisifretext.setBackground(new java.awt.Color(255, 255, 255));
        musterisifretext.setForeground(new java.awt.Color(0, 0, 0));
        musterisifretext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musterisifretextActionPerformed(evt);
            }
        });

        musterigirisbuton.setText("giriş");
        musterigirisbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musterigirisbutonActionPerformed(evt);
            }
        });

        jLabel2.setText("sifre: ");

        jLabel1.setText("T.C no:");

        musterilogincıkısbuton.setText("çıkış");
        musterilogincıkısbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musterilogincıkısbutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(musteritctext)
                                        .addComponent(musterisifretext, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 47, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(musterilogincıkısbuton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(girislog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(musterigirisbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(musterilogincıkısbuton)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musteritctext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musterisifretext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(musterigirisbuton)
                .addGap(18, 18, 18)
                .addComponent(girislog)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void musterilogincıkısbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musterilogincıkısbutonActionPerformed
        MainPageGUI mp = new MainPageGUI();
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_musterilogincıkısbutonActionPerformed

    private void musterigirisbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musterigirisbutonActionPerformed
        Musteri m = new Musteri();
        m.setTc(musteritctext.getText());
        m.setSifre(musterisifretext.getText());
        if (musteritctext.getText().length() == 0 || musterisifretext.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "lüten gerekli yerleri eksiksiz dolduralım");
        }
        else if(musteritctext.getText().length() >11){
             JOptionPane.showMessageDialog(null, "lütfen geçerli bir tc  giriniz!!");
        }
        else if(musterisifretext.getText().length() > 30){
            JOptionPane.showMessageDialog(null, "lütfen geçerli şifre  giriniz!!");
        }
        else {
            //String sorgu = "SELECT * FROM bireyselmusteri WHERE tc=? AND sifre=?";
            if (m.girisYap(m.getTc(),m.getSifre())) {
                try {
                    JOptionPane.showMessageDialog(null, "bilgiler doğru giriş yapılıyor...");
                    
                    MusteriGUI mg = new MusteriGUI(m);
                    mg.setVisible(true);
                    
                    dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(MusteriLoginGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                //girislog.setText("tc no veya şifre hatalı lütfen kontrol edelim");
                JOptionPane.showMessageDialog(null, "tc no veya şifre hatalı lütfen kontrol edelim");
            }
        }

    }//GEN-LAST:event_musterigirisbutonActionPerformed

    private void musteritctextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteritctextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musteritctextActionPerformed

    private void musterisifretextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musterisifretextActionPerformed


    }//GEN-LAST:event_musterisifretextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriLoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel girislog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton musterigirisbuton;
    private javax.swing.JButton musterilogincıkısbuton;
    private javax.swing.JPasswordField musterisifretext;
    private javax.swing.JTextField musteritctext;
    // End of variables declaration//GEN-END:variables
}
