/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_wiev;

import Backend.Kasa;
import Backend.Log;
import Backend.Musteri;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import veritabani.Veritabani;
import static veritabani.Veritabani.conn;

/**
 *
 * @author yahya
 */
public class ParaYatirGUI extends javax.swing.JFrame {

    /**
     * Creates new form ParaYatirGUI
     */
    Double para = null;
    String tc = null;
    String stringbakiye = null;

    public ParaYatirGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public ParaYatirGUI(Musteri m, String bakiye) {

        initComponents();
        para = m.getVarlik();
        tc = m.getTc();
        //System.out.println(para);
        // System.out.println(m.getVarlik());
        stringbakiye = bakiye;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eklenecekbakiye = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        onaycheckbox = new javax.swing.JCheckBox();
        yatirbuton = new javax.swing.JButton();
        iptalbuton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("para yatır");
        setResizable(false);

        eklenecekbakiye.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("miktar:");

        onaycheckbox.setText("onayla");

        yatirbuton.setText("yatır");
        yatirbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yatirbutonActionPerformed(evt);
            }
        });

        iptalbuton.setText("iptal");
        iptalbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptalbutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eklenecekbakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(onaycheckbox)
                            .addComponent(yatirbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(iptalbuton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iptalbuton)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eklenecekbakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(onaycheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(yatirbuton)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yatirbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yatirbutonActionPerformed
        Double temp = Double.parseDouble(eklenecekbakiye.getText());
        Musteri m = new Musteri();
        m.setTc(tc);
        m.setVarlik(para);
        if (eklenecekbakiye.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, " lütfen yatıralacak olan miktarı giriniz! ");
        } else if (!onaycheckbox.isSelected()) {
            JOptionPane.showMessageDialog(null, "lütfen onay kutucuğunu işaretleyiniz! ");
        } else {
            int res = JOptionPane.showConfirmDialog(null, "yatıralacak olan miktarı onaylıyor musunuz", "onay", JOptionPane.YES_NO_OPTION);
            if (res == 0) {

                try {
                    para = m.parayatir(para, temp, tc);
                    m.setVarlik(para);
                    JOptionPane.showMessageDialog(null, "işleminiz gerçekleşmiştir... ");
                    String log = String.valueOf(temp) + " kadar para yatırıldı";
                    Log.logekle(tc, log);
                    MusteriGUI mg = new MusteriGUI(m);
                    mg.setVisible(true);
                    dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(ParaYatirGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (res == 1) {
                try {
                    JOptionPane.showMessageDialog(null, "işleminiz iptal edilmiştir");
                    MusteriGUI mg = new MusteriGUI(m);
                    mg.setVisible(true);
                    dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(ParaYatirGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_yatirbutonActionPerformed

    private void iptalbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptalbutonActionPerformed
        try {
            Musteri m = new Musteri();
            m.setTc(tc);
            m.setVarlik(para);
            MusteriGUI mg = new MusteriGUI(m);
            mg.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(ParaYatirGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_iptalbutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParaYatirGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParaYatirGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParaYatirGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParaYatirGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParaYatirGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eklenecekbakiye;
    private javax.swing.JButton iptalbuton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox onaycheckbox;
    private javax.swing.JButton yatirbuton;
    // End of variables declaration//GEN-END:variables
}
