/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_wiev;

import Backend.Kasa;
import Backend.Log;
import Backend.Musteri;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import veritabani.Veritabani;
import static veritabani.Veritabani.conn;

/**
 *
 * @author yahya
 */
public class ParaCekGUI extends javax.swing.JFrame {

    /**
     * Creates new form ParaCekGUI
     */
    Double para = null;
    String tc = null;

    public ParaCekGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public ParaCekGUI(Musteri m) {
        initComponents();
        para = m.getVarlik();
        tc = m.getTc();
        setLocationRelativeTo(null);
    }

//    public static boolean paracek(Double ilkpara, Double cekilenpara, String paracekilentc) throws SQLException {
//        Veritabani.baglan();
//        String sorgu = "UPDATE bireyselmusteri SET varlik=? WHERE tc=?";
//        if (cekilenpara > ilkpara) {
//            //JOptionPane.showMessageDialog(null, "yetersiz bakiye");
//            return false;
//
//        } else {
//            PreparedStatement ps = conn.prepareStatement(sorgu);
//            ps.setDouble(1, (ilkpara - cekilenpara));
//            ps.setString(2, paracekilentc);
//            ps.executeUpdate();
//            Kasa.kasadancik(cekilenpara);
//            return true;
//        }
//
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cekilecekbakiyetext = new javax.swing.JTextField();
        paracekbuton = new javax.swing.JButton();
        paracekonaycheckbox = new javax.swing.JCheckBox();
        iptalbuton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("para çek");

        jLabel1.setText("cekilecek tutar");

        cekilecekbakiyetext.setToolTipText("cekilecek para tutarını giriniz");

        paracekbuton.setText("onayla");
        paracekbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paracekbutonActionPerformed(evt);
            }
        });

        paracekonaycheckbox.setText("onayla");

        iptalbuton.setText("iptal");
        iptalbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptalbutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paracekonaycheckbox)
                    .addComponent(paracekbuton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(cekilecekbakiyetext, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iptalbuton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iptalbuton)
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cekilecekbakiyetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(paracekonaycheckbox)
                .addGap(18, 18, 18)
                .addComponent(paracekbuton)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paracekbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paracekbutonActionPerformed
        Musteri m = new Musteri();
        m.setTc(tc);
        m.setVarlik(para);
        if (cekilecekbakiyetext.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "lütfen cekilecek olan miktari giriniz");
        } else if (Integer.parseInt(cekilecekbakiyetext.getText()) <= 0) {
            JOptionPane.showMessageDialog(null, "lütfen geçerli bir değer giriniz");
        } else if (!paracekonaycheckbox.isSelected()) {
            JOptionPane.showMessageDialog(null, "lütfen onay kutucuğunu işaretleyiniz! ");
        } else {
            int res = JOptionPane.showConfirmDialog(null, "cekilecek olan miktarı onaylıyor musunuz", "onay", JOptionPane.YES_NO_OPTION);
            if (res == 0) {
                Double temp = Double.parseDouble(cekilecekbakiyetext.getText());
                if (!m.paracek(para, temp, tc)) {
                    JOptionPane.showMessageDialog(null, "yetersiz bakiye");
                    cekilecekbakiyetext.setText("");
                } else {
                    try {
                        JOptionPane.showMessageDialog(null, "işleminiz gerçekleşmiştir... ");
                        //Musteri m = new Musteri();
                        String log=String.valueOf(temp)+" kadar para çekildi";
                        Log.logekle(tc, log);
                        m.setTc(tc);
                        m.setVarlik(para - temp);
                        MusteriGUI mg = new MusteriGUI(m);
                        mg.setVisible(true);
                        dispose();
                    } catch (SQLException ex) {
                        Logger.getLogger(ParaCekGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
            if (res == 1) {
                try {
                    JOptionPane.showMessageDialog(null, "işleminiz iptal edilmiştir");
                    m.setTc(tc);
                    m.setVarlik(para);
                    MusteriGUI mg = new MusteriGUI(m);
                    mg.setVisible(true);
                    dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(ParaCekGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_paracekbutonActionPerformed

    private void iptalbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptalbutonActionPerformed
        try {
            Musteri m = new Musteri();
            m.setTc(tc);
            m.setVarlik(para);
            MusteriGUI mg = new MusteriGUI(m);
            mg.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(ParaCekGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_iptalbutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParaCekGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParaCekGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParaCekGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParaCekGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParaCekGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cekilecekbakiyetext;
    private javax.swing.JButton iptalbuton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton paracekbuton;
    private javax.swing.JCheckBox paracekonaycheckbox;
    // End of variables declaration//GEN-END:variables
}
